### ISSUE TITLE
What about location descriptions?

### ISSUE THREAD

**Issue by janson** [downtowngr/mantle#6]
At the moment, descriptions aren't being sent over in the location api endpoint. Rather than have those descriptions as just a part of pearl, I suspect we'll want this to be synced as well.

**Comment by pichot** [comment]
So here's the challenge: Facebook provides `about`, `description`, `mission`, and even `general_info` that pages can use to describe themselves. A cursory look at different pages shows that businesses use those sections differently, and many times the content isn't very good. Since we can't consistently tell where to get a good description, at the moment I'm think we'll be entering these in manually. :grimacing:

**Comment by janson** [comment]
Hmmmm... ok. We'll leave that field in Craft for now, with the assumption that it'll be populated manually.

What about also making an educated/executive decision and picking one of those FB fields for Mantle to return? Then later down the road, DGRI can tell businesses where to fill in that information on FB, and a later minor update to Pearl can consume that data already being sent over via Mantle.
